package com.sfl.coolmonkey.emailtemplate.service.emailtemplate.model;

/**
 * User: Arthur Asatryan
 * Company: SFL LLC
 * Date: 10/22/15
 * Time: 5:56 PM
 */
public enum SystemEmailTemplateType {
    TM_ADMIN_ACCOUNT_ACTIVATED,
    TM_ADMIN_EMAIL_UPDATED,
    TM_AGENT_ACCOUNT_ACTIVATED,
    TM_ADMIN_FORGOT_PASSWORD,
    TM_ADMIN_PASSWORD_CHANGE,
    TM_ADMIN_SIGN_UP_CONFIRM,
    ADDRESS_IMPORT_SUCCEED,
    ADDRESS_IMPORT_FAILED,
    PAYMENT_ORDER,
    PAYMENT_INVOICE,
    AUTO_RECHARGE_PERIODICAL_REMINDER,
    AUTO_RECHARGE_PPCA_REMINDER,
    NO_ENOUGH_BALANCE_TO_AUTORECHARGE,
    CREDITS_ALLOCATED_SUCCESSFULLY,
    TM_AGENT_SUBSCRIPTION_CREATED,
    TM_ADMIN_CREDITS_REMINDER,
    SUBSCRIPTION_CANCELLED,
    CALL_CENTER_ADMIN_PERMISSION_REQUEST,
    ACCEPT_PERMISSION_REQUEST,
    REJECT_PERMISSION_REQUEST,
    DISCONNECT_CALL_CENTER,
    CUSTOMER_EMPLOYEE_ACCOUNT_ACTIVATED,
    CUSTOMER_EMPLOYEE_AGENT_ACCOUNT_ACTIVATED,
    CALL_CENTER_SIGN_UP_CONFIRM,
    CALL_CENTER_TM_AGENT_ACCOUNT_ACTIVATED,
    CALL_CENTER_ACCOUNT_ACTIVATED,
    AGENT_REMOVE_CANCEL_SUBSCRIPTIONS,
    ADDRESS_EXPORT_SUCCEED
}
